#!/usr/bin/env python3
"""Phase 49: table-family COVERAGE MATRIX (generated, read-only, no long scans).

Emits Outputs/coverage_matrix.csv + coverage_matrix.md: one row per table
*family* (Call, UBPR, FDIC-SDI, Y-9C/BHCF, Y-15, Pillar-3, UBPR-rank, HMDA,
NIC attributes, FRED, OCC historical, failures, ...) with:
  family | tables | base_rows | period_min | period_max | date_grain
        | provenance_tier(s) | provider(s) | completeness_note | span_source

CHEAP BY CONSTRUCTION. Row counts + period spans come from the in-DB
`main.freenic_manifest` table (110 rows, regenerated by 47_self_describing.py),
NOT from MIN/MAX over the billion-row filing tables. Provider/tier come from
Outputs/PROVENANCE.csv. Completeness notes are the documented upstream-boundary
facts from COVERAGE_GAPS.md. The only DB read is a SELECT over the 110-row
manifest table (read_only connection); no base-table scan occurs.

span_source is 'manifest' for every family (the authoritative cheap path); if a
family's period is not carried in the manifest it is 'docs' (from PROVENANCE.csv
era text) and marked so the site methodology page can cite it honestly.

Run:  PYTHONIOENCODING=utf-8 python 49_coverage_matrix.py
"""
import csv
import io
import re
from pathlib import Path

import duckdb

HERE = Path(__file__).resolve().parent
OUT = HERE.parent.parent.parent / "Outputs"
DB = OUT / "freenic.duckdb"
PROV = OUT / "PROVENANCE.csv"
CSV_OUT = OUT / "coverage_matrix.csv"
MD_OUT = OUT / "coverage_matrix.md"

# ---------------------------------------------------------------------------
# Family assignment: base table -> family label. One row per family in output.
# Tables not listed fall into a catch-all "Reference / crosswalks" family.
# ---------------------------------------------------------------------------
FAMILY = {
    # Call Reports (Fed-direct micro) + pre-1976 Luck core + unrealized-loss layer
    "call_report_filings": "Call Reports (FFIEC/Fed micro)",
    "luck_call_reports": "Call Reports (FFIEC/Fed micro)",
    "cdr_unrealized_losses": "Call Reports (FFIEC/Fed micro)",
    "filing_metadata": "Call Reports (FFIEC/Fed micro)",
    # UBPR analytical ratios
    "ubpr_ratios": "UBPR ratios",
    # UBPR peer statistics (percentile benchmarks)
    "ubpr_peer_stats": "UBPR peer stats",
    # UBPR per-bank peer rank
    "ubpr_peer_rank": "UBPR peer rank",
    # FR Y-9C consolidated holding-company (BHCF)
    "bhcf_filings": "FR Y-9C / BHCF (holding cos)",
    # FDIC Statistics on Depository Institutions
    "fdic_financials": "FDIC SDI (financials)",
    "fdic_sdi_features": "FDIC SDI (financials)",
    # FDIC Summary of Deposits (branch)
    "fdic_sod": "FDIC SOD (branch deposits)",
    # FDIC failures + structure history
    "bank_failures": "FDIC failures / history",
    "fdic_history": "FDIC failures / history",
    # Stress testing
    "dfast_results": "DFAST / stress tests",
    "stress_scenarios": "DFAST / stress tests",
    "stress_scenarios_domestic": "DFAST / stress tests",
    "stress_scenarios_international": "DFAST / stress tests",
    # Basel Pillar 3 disclosures
    "pillar3_disclosures": "Pillar 3 (G-SIB disclosures)",
    # FR Y-15 systemic indicators
    "y15_systemic_indicators": "FR Y-15 (systemic indicators)",
    # HMDA mortgage lending summary
    "hmda_summary": "HMDA (mortgage summary)",
    # NCUA credit-union 5300
    "ncua_5300": "NCUA 5300 (credit unions)",
    "ncua_cu_directory": "NCUA 5300 (credit unions)",
    # NIC identity / attributes / structure
    "institutions": "NIC identity & attributes",
    "institution_attributes": "NIC identity & attributes",
    "nic_attributes_ext": "NIC identity & attributes",
    "nic_entity_identifiers": "NIC identity & attributes",
    "branches": "NIC identity & attributes",
    "relationships": "NIC identity & attributes",
    "transformations": "NIC identity & attributes",
    "bhc_ownership": "NIC identity & attributes",
    "entity_xref": "NIC identity & attributes",
    # OCC historical national-bank balance sheets
    "occ_historical": "OCC historical (1863-1941)",
    # Robin / Failing Banks derived panels
    "robin_panel_base": "Robin / Failing Banks (derived)",
    "robin_deposits_historical": "Robin / Failing Banks (derived)",
    "robin_deposits_modern": "Robin / Failing Banks (derived)",
    "robin_crosswalk": "Robin / Failing Banks (derived)",
    # Clean from-raw canonical bank panel (163-yr $ levels)
    "clean_bank_panel": "Clean bank panel (163-yr $ levels)",
    # FRED / H.8 macro-banking context
    "fred_series": "FRED / H.8 (macro context)",
    # Identity crosswalks / MDRM / reference
    "mdrm": "Reference / crosswalks",
    "id_crosswalk": "Reference / crosswalks",
    "crsp_mapping": "Reference / crosswalks",
    "sec_cik_crosswalk": "Reference / crosswalks",
    "sector_groupings": "Reference / crosswalks",
    "variable_crosswalk": "Reference / crosswalks",
    "reporting_forms": "Reference / crosswalks",
}
DICT_FAMILY = "Data dictionary (dict.*)"
CATALOG_FAMILY = "Warehouse catalog (catalog.*)"
DEFAULT_FAMILY = "Reference / crosswalks"

# ---------------------------------------------------------------------------
# Documented completeness notes per family (from COVERAGE_GAPS.md, authoritative).
# ---------------------------------------------------------------------------
NOTES = {
    "Call Reports (FFIEC/Fed micro)":
        "Full modern micro history 1976Q1-2026Q1 (Chicago Fed pre-2012 + FFIEC CDR 2012+); "
        "pre-1976 covered by the Luck 1959Q4-1975Q4 core (kept only where Fed-direct is absent); "
        "cdr_unrealized_losses adds the RC-B/AOCI fair-value layer 2019Q4-2025Q4. CURRENT.",
    "UBPR ratios":
        "Full CDR extent 2002Q4-2026Q1 (94 periods; 2002 Q1-Q3 not offered by CDR - upstream floor). CURRENT.",
    "UBPR peer stats":
        "FFIEC peer-group percentile benchmarks 2002Q1-2026. CURRENT.",
    "UBPR peer rank":
        "Per-bank percentile rank SCOPED 2021-2024 to align 1:1 with the ubpr_ratios panel; "
        "full 25-yr history (~2.1B rows) is a documented resumable extension, deferred as disproportionate.",
    "FR Y-9C / BHCF (holding cos)":
        "Consolidated BHC filings 1986Q3-2025Q4. TRAILS one quarter at 2025Q4 - Y-9C 2026Q1 publishes "
        "later than Call/UBPR/SDI (upstream lag), not a gap.",
    "FDIC SDI (financials)":
        "Statistics on Depository Institutions 1984Q1-2026Q1 + engineered SDI feature/failure-flag panel. CURRENT.",
    "FDIC SOD (branch deposits)":
        "Summary of Deposits branch-level 1994-2025 (annual survey; 2026 publishes ~Oct). CURRENT.",
    "FDIC failures / history":
        "Failure/assistance events 1934-2026 + structure-change history (effective dates from 1782). "
        "Public FDIC undercounts pre-1980 assisted-merger distress (see COVERAGE_GAPS C4).",
    "DFAST / stress tests":
        "Supervisory stress-test results 2013-2025 + macro scenario paths (historical actuals + projections).",
    "Pillar 3 (G-SIB disclosures)":
        "ALL 8 US G-SIBs (JPM/BAC/C/WFC/MS/GS/BK/STT) but few quarters only (2024Q1-2025Q3); "
        "PDF-extracted from investor-relations disclosures - narrow by design.",
    "FR Y-15 (systemic indicators)":
        "G-SIB systemic-risk indicators 2020-2024 = the FULL NIC-published snapshot extent; "
        "no pre-2020 bulk product exists (upstream boundary, not a gap).",
    "HMDA (mortgage summary)":
        "Institution x year mortgage-lending summary (NOT full LAR) 2018-2024 via CFPB Data Browser; "
        "pre-2018 NO-GO (Data Browser covers 2018+ only). Micro LAR routes OUT to hmdaexplore.",
    "NCUA 5300 (credit unions)":
        "Credit-union 5300 call reports FULL history 1994Q1-2025Q4 (128 periods, 13,535 CUs) + CU directory. "
        "Scope expansion beyond FDIC-insured/BHC universe. CURRENT.",
    "NIC identity & attributes":
        "FFIEC NIC entity master, attributes, multi-regulator ID crosswalk, branches, ownership hierarchy, "
        "predecessor/successor transformations, and entity_xref (234,462 rssds). Current snapshot.",
    "OCC historical (1863-1941)":
        "National-bank balance sheets 1863-1941 (two stacked vintages: OCC 1867-1904 + finhist/CLV 1863-1941; "
        "filter by source - see COVERAGE_GAPS C3). Quarterly 1942-1958 gap = physical archives only.",
    "Robin / Failing Banks (derived)":
        "Correia-Luck-Verner Failing Banks annual panel 1863-2024 + pre/post deposit-dynamics panels. "
        "robin_panel absolute-$ columns are uncalibrated (guarded view) - use clean_bank_panel for $ levels.",
    "Clean bank panel (163-yr $ levels)":
        "CANONICAL from-raw nominal+real $ bank panel 1863-2026 (finhist-primary); the fix for robin_panel's "
        "uncalibrated columns.",
    "FRED / H.8 (macro context)":
        "FRED H.8 + macro/banking series to warehouse MAX(period_end) 2026-05-29 (monthly). CURRENT.",
    "Reference / crosswalks":
        "MDRM variable dictionary + identity crosswalks (RSSD<->cert<->CIK<->LEI) + form taxonomy + concept map. Reference.",
    DICT_FAMILY:
        "bank-data-dictionary v10.0 (7 tables): crosswalk, edit history, schedule line-items, UBPR concepts, "
        "reconciliation registry, variable access map (15,435 vars, >=1-view reachability PASS).",
    CATALOG_FAMILY:
        "Warehouse self-describing catalog (6 tables): data_sources, variables, schema evolution/coverage. Reference.",
}


def parse_span(span):
    """Return (grain_label, min, max) from a manifest period_span like
    'period_end: 1976-03-31 .. 2026-03-31' or 'year: 1994 .. 2025'."""
    if not span:
        return ("", "", "")
    m = re.match(r"\s*([A-Za-z_]+)\s*:\s*(.+?)\s*\.\.\s*(.+?)\s*$", span)
    if not m:
        return ("", "", "")
    grain, lo, hi = m.group(1), m.group(2).strip(), m.group(3).strip()
    # strip trailing 00:00:00 timestamps
    lo = lo.split(" ")[0]
    hi = hi.split(" ")[0]
    return (grain, lo, hi)


def load_provenance():
    """table -> (set(tiers), set(providers)) from PROVENANCE.csv."""
    prov = {}
    with io.open(PROV, "r", encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            t = row["table"]
            prov.setdefault(t, (set(), set()))
            if row.get("provenance_tier"):
                prov[t][0].add(row["provenance_tier"])
            if row.get("provider"):
                prov[t][1].add(row["provider"])
    return prov


def main():
    con = duckdb.connect(str(DB), read_only=True)
    # ONLY read: the 110-row manifest. No base-table scan.
    rows = con.execute("""
        SELECT name, kind, schema, row_count, period_span
        FROM main.freenic_manifest
        WHERE kind = 'table'
        ORDER BY row_count DESC NULLS LAST
    """).fetchall()
    con.close()

    prov = load_provenance()

    # Accumulate per family.
    fam = {}  # family -> dict
    for name, kind, schema, rc, span in rows:
        if schema == "dict":
            family = DICT_FAMILY
        elif schema == "catalog":
            family = CATALOG_FAMILY
        else:
            family = FAMILY.get(name, DEFAULT_FAMILY)
        grain, lo, hi = parse_span(span)
        f = fam.setdefault(family, {
            "tables": [], "rows": 0, "grains": set(),
            "mins": [], "maxs": [], "tiers": set(), "providers": set(),
        })
        f["tables"].append(name)
        f["rows"] += int(rc or 0)
        if grain:
            f["grains"].add(grain)
        if lo:
            f["mins"].append(lo)
        if hi:
            f["maxs"].append(hi)
        p = prov.get(name)
        if p:
            f["tiers"].update(p[0])
            f["providers"].update(p[1])

    # Order families by total rows desc.
    ordered = sorted(fam.items(), key=lambda kv: -kv[1]["rows"])

    def norm_date(d):
        # pad bare year to sortable form
        return d if len(d) > 4 else d + "-00-00"

    records = []
    for family, f in ordered:
        mins = sorted(f["mins"], key=norm_date)
        maxs = sorted(f["maxs"], key=norm_date)
        pmin = mins[0] if mins else ""
        pmax = maxs[-1] if maxs else ""
        span_source = "manifest" if (pmin or pmax) else "docs (no dated grain)"
        records.append({
            "family": family,
            "n_tables": len(f["tables"]),
            "tables": "; ".join(sorted(f["tables"])),
            "base_rows": f["rows"],
            "period_min": pmin,
            "period_max": pmax,
            "date_grain": "/".join(sorted(f["grains"])) if f["grains"] else "(no time axis)",
            "provenance_tier": "/".join(sorted(f["tiers"])) if f["tiers"] else "",
            "provider": " | ".join(sorted(f["providers"])) if f["providers"] else "",
            "completeness_note": NOTES.get(family, ""),
            "span_source": span_source,
        })

    # --- CSV ---
    cols = ["family", "n_tables", "tables", "base_rows", "period_min", "period_max",
            "date_grain", "provenance_tier", "provider", "completeness_note", "span_source"]
    with io.open(CSV_OUT, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=cols, lineterminator="\n")
        w.writeheader()
        w.writerows(records)

    # --- Markdown ---
    total_rows = sum(r["base_rows"] for r in records)
    lines = []
    lines.append("# FreeNIC Coverage Matrix")
    lines.append("")
    lines.append("_One row per table family. Generated by "
                 "`Technical/freenic_ingestion/scripts/49_coverage_matrix.py` — "
                 "READ-ONLY, no billion-row scans (row counts + period spans read "
                 "from the in-DB `main.freenic_manifest`, regenerated by "
                 "`47_self_describing.py`; provider/tier from `Outputs/PROVENANCE.csv`; "
                 "completeness notes from `COVERAGE_GAPS.md`)._")
    lines.append("")
    lines.append(f"**Families:** {len(records)} · "
                 f"**Base tables covered:** {sum(r['n_tables'] for r in records)} · "
                 f"**Total base rows:** {total_rows:,}")
    lines.append("")
    lines.append("| Family | Tables | Base rows | Period (min–max) | Grain | Tier | Completeness note |")
    lines.append("|---|--:|--:|---|---|---|---|")
    for r in records:
        span = (f"{r['period_min']} – {r['period_max']}"
                if r["period_min"] else "(no time axis)")
        lines.append(
            f"| {r['family']} | {r['n_tables']} | {r['base_rows']:,} | {span} | "
            f"{r['date_grain']} | {r['provenance_tier']} | {r['completeness_note']} |")
    lines.append("")
    lines.append("### Table membership per family")
    lines.append("")
    for r in records:
        lines.append(f"- **{r['family']}** ({r['provider'] or 'derived'}): {r['tables']}")
    lines.append("")
    with io.open(MD_OUT, "w", encoding="utf-8", newline="") as f:
        f.write("\n".join(lines))

    print(f"coverage matrix: {len(records)} families, "
          f"{sum(r['n_tables'] for r in records)} base tables, "
          f"{total_rows:,} rows")
    print(f"  -> {CSV_OUT}")
    print(f"  -> {MD_OUT}")
    for r in records:
        span = f"{r['period_min']}..{r['period_max']}" if r["period_min"] else "-"
        print(f"    {r['family']:<38} {r['n_tables']:>2}t {r['base_rows']:>14,}  {span}")


if __name__ == "__main__":
    main()
