"""FreeNIC — public data explorer (FastAPI + DuckDB + Plotly).

A thin explorer over a SMALL REAL CURATED SLICE of the FreeNIC open banking dataset.
The full FreeNIC data is the ~13.2 GiB / 61-file v1.0.0 parquet release (~4.97B rows,
58 base tables, 217,210 institutions, 20 sources, 1863-2026) and is reachable via the R/Python
packages + API over the published parquet release. This site ships ONLY a ~5 MB
curated sample of real, published tables (FDIC bank failures, FRED banking series,
active institutions) plus a few precomputed aggregates, so it can be browsed and
charted without the full corpus.

Nothing on this site is fabricated — every row is a real subset of the published
data. The browsable explorer is a curated sample; the complete dataset is accessed
via the R/Python package and API.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import duckdb
from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.responses import HTMLResponse, JSONResponse, PlainTextResponse, Response
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

from carson_telemetry import telemetry  # Carson Telemetry Standard §4 (Layer-3 usage events)

from app import chrome  # Arcanum Site Kit (ASK) v1 — shared-chrome context processor
from app import downloads  # Wave-3 /data + /code download catalog (real slice tables)

BASE = Path(__file__).resolve().parent
DATA = BASE / "data"
DB_PATH = DATA / "freenic_slice.duckdb"
STATIC = BASE / "static"


def _asset_ver(static_dir) -> str:
    """Short content hash of the vendored kit (_shared) + site css/js — changes
    whenever any of those change, so ?v=<hash> busts the CDN cache on deploy."""
    import hashlib
    h = hashlib.md5()
    root = Path(static_dir)
    for sub in ("_shared", "css", "js"):
        d = root / sub
        if not d.exists():
            continue
        for p in sorted(d.rglob("*")):
            if p.is_file():
                try:
                    h.update(p.read_bytes())
                except Exception:  # noqa: BLE001
                    pass
    return h.hexdigest()[:8]


app = FastAPI(title="FreeNIC - open banking data explorer")
# Carson telemetry (TELEMETRY_STANDARD.md §4) — Layer-3 usage events: one
# usage_events row per request into the shared SQLite DB at $CARSON_TELEMETRY_DB.
# Mirrors leontief's wiring (carson-telemetry is vendored under deploy/freenic/vendor).
app.add_middleware(telemetry.ASGIMiddleware, service="freenic")
app.mount("/static", StaticFiles(directory=str(BASE / "static")), name="static")
# context_processors=[chrome.ark_context] injects the ASK shared-chrome vars
# (site_key, site_title, site_home, dpr_url, ecosystem, nav) into EVERY
# TemplateResponse — no per-route changes needed.
templates = Jinja2Templates(
    directory=str(BASE / "templates"),
    context_processors=[chrome.ark_context],
)
# asset_ver: short content-hash of the vendored kit + site static, stamped as
# ?v=<hash> on asset URLs so a kit/CSS/JS change busts the Cloudflare cache
# automatically (the box has no CF purge token; kit assets are cached 4h).
templates.env.globals["asset_ver"] = _asset_ver(STATIC)

# CDF single source of truth: EVERY on-page count renders from freenic_counts.json
# (generated by make_freenic_counts.py from the served host + the slice DB) — never
# hand-typed. Templates read `{{ counts.release_files }}`, `{{ counts.slice_zip_h }}`,
# etc. Loaded once as a Jinja global so it is available in every render.
try:
    with open(DATA / "freenic_counts.json", encoding="utf-8") as _cf:
        templates.env.globals["counts"] = json.load(_cf)
except Exception:  # noqa: BLE001 — never break a render if the file is missing
    templates.env.globals["counts"] = {}


def _con() -> duckdb.DuckDBPyConnection:
    """Read-only connection to the baked curated slice."""
    return duckdb.connect(str(DB_PATH), read_only=True)


def _rows(sql: str, params: list | None = None) -> list[dict]:
    con = _con()
    try:
        cur = con.execute(sql, params or [])
        cols = [d[0] for d in cur.description]
        return [dict(zip(cols, r)) for r in cur.fetchall()]
    finally:
        con.close()


def _jsonable(v):
    """Coerce non-JSON-native values (date/datetime/Decimal) to JSON-safe types."""
    if v is None or isinstance(v, (str, int, float, bool)):
        return v
    return str(v)


def _load_json(name: str) -> dict:
    with open(DATA / name, "r", encoding="utf-8") as fh:
        return json.load(fh)


SOURCES = _load_json("sources.json")
# Dictionary content layer (merged from the reviewed staging files at build time;
# see build_content.py). Schedule/layer/category explanations + the annotated
# supplier directory. Non-fatal if absent so a render never breaks.
try:
    EXPLANATIONS = _load_json("explanations.json")
except Exception:  # noqa: BLE001
    EXPLANATIONS = {"schedules": {}, "layers": {}, "categories": {}}
try:
    SOURCES_DIRECTORY = _load_json("sources_directory.json")
except Exception:  # noqa: BLE001
    SOURCES_DIRECTORY = {"sources": []}

# The real slice tables/views browsable on this site (drives the /explorer
# catalog, the /api-docs access matrix, and the /methodology provenance panel).
SLICE_TABLES = {
    "bank_failures",
    "fred_series",
    "institutions_active",
    "agg_failures_by_year",
    "agg_failures_by_state",
    "agg_institutions_by_state",
    "agg_institutions_by_type",
    "fred_catalog",
    # the replicated 163-year bank-aggregate spine (year x metric, 1863-2026)
    "long_bank_aggregates_1863_2026",
    # dict taxonomy slice (version-pinned bank-data-dictionary v10.0)
    "dict_schedule_lineitems",
    "dict_ubpr_concepts",
    "dict_variable_access_map",
    "dict_relationships_summary",
    "dict_meta",
}

# Canonical reference site for the taxonomy (the public bank-data-dictionary).
DICT_REF_BASE = "https://andenick.github.io/bank-data-dictionary/"
# Form families whose schedule-guide pages have a predictable slug at the ref site.
_DICT_GUIDE_FAMILIES = {"call", "y9c", "ubpr"}


def _dict_meta() -> dict:
    """The dict taxonomy meta (version, repo) as a {key: value} dict."""
    try:
        return {r["key"]: r["value"] for r in _rows("SELECT key, value FROM dict_meta")}
    except Exception:  # noqa: BLE001 — never break the page on a missing table
        return {}


def _dict_ref_url(form_family: str | None, schedule: str | None) -> str:
    """Deep-link the canonical reference site where the slug is predictable.

    The reference site publishes per-form schedule guides; when the form family is
    one of the known guide families we deep-link its guide page, otherwise we fall
    back to the site root. No workspace paths — public URL only.
    """
    fam = (form_family or "").strip().lower()
    if fam in _DICT_GUIDE_FAMILIES:
        return f"{DICT_REF_BASE}guides/{fam}/"
    return DICT_REF_BASE


# ---------------- pages ----------------

@app.get("/healthz", response_class=PlainTextResponse)
def healthz() -> str:
    return "ok"


@app.get("/llms.txt", response_class=PlainTextResponse)
def llms_txt() -> PlainTextResponse:
    """Agent-discoverability manifest (CDF §B2.4) — generated from ecosystem.json's
    freenic `cdf` block by the kit make_llms_txt.py tool and vendored at build."""
    p = STATIC / "llms.txt"
    if p.exists():
        return PlainTextResponse(p.read_text(encoding="utf-8"))
    raise HTTPException(status_code=404, detail="llms.txt not generated")


@app.get("/", response_class=HTMLResponse)
def index(request: Request) -> HTMLResponse:
    return templates.TemplateResponse(
        "index.html", {"request": request, "sources": SOURCES["sources"]}
    )


@app.get("/explorer", response_class=HTMLResponse)
def explorer(request: Request) -> HTMLResponse:
    # table-name + rough row count for the catalog shown in the explorer
    tables = []
    for t in sorted(SLICE_TABLES):
        n = _rows(f"SELECT COUNT(*) AS n FROM {t}")[0]["n"]
        tables.append({"name": t, "rows": n})
    return templates.TemplateResponse(
        "explorer.html", {"request": request, "tables": tables}
    )


@app.get("/institutions", response_class=HTMLResponse)
def institutions(request: Request) -> HTMLResponse:
    """Institution lookup over the real active-institutions slice: search by name
    or RSSD/FDIC-cert, filter by entity type and state, browse key attributes with
    honest gaps, and download the results. All data client-fetched from the real
    /api/institution_facets + /api/lookup_institution endpoints."""
    n_active = _rows("SELECT COUNT(*) AS n FROM institutions_active")[0]["n"]
    return templates.TemplateResponse(
        "institutions.html", {"request": request, "n_active": n_active}
    )


@app.get("/failures", response_class=HTMLResponse)
def failures(request: Request) -> HTMLResponse:
    """Bank-failure explorer over the real bank_failures slice: failures-per-year
    timeline (the 1863–2026 framing tie-in), era/state/resolution filters, a table
    view with CSV download, and honest FDIC/Robin provenance."""
    stats = _rows(
        "SELECT COUNT(*) AS n, MIN(failure_year) AS lo, MAX(failure_year) AS hi "
        "FROM bank_failures"
    )[0]
    return templates.TemplateResponse(
        "failures.html",
        {"request": request, "n_failures": stats["n"],
         "year_min": stats["lo"], "year_max": stats["hi"]},
    )


# ---------------- /dictionary — taxonomized explorer ----------------

_DICT_PAGE_SIZE = 200  # hard cap of result rows per page

# Source-family taxonomy: the landing tree groups schedules/layers under these.
# (label, category-key in explanations.json, the form_family value in the dict
# line-item table OR None for derivation layers that have no line-item schedules.)
_DICT_FAMILIES: list[dict] = [
    {"key": "y9c",  "label": "FR Y-9C", "family": "y9c",  "kind": "schedules"},
    {"key": "call", "label": "Call Report", "family": "call", "kind": "schedules"},
    {"key": "ubpr", "label": "UBPR", "family": None, "kind": "layer", "layer": "ubpr"},
    {"key": "fdic", "label": "FDIC", "family": None, "kind": "layer", "layer": "fdic"},
    {"key": "historical", "label": "Historical", "family": None,
     "kind": "layer", "layer": "luck_historical"},
]


def _schedule_slug(form_family: str, schedule: str) -> str:
    """Filesystem/URL-safe slug for a schedule's per-schedule CSV file."""
    return f"{form_family}_{schedule}".replace("/", "-").replace(" ", "_")


def _dict_schedule_index() -> dict[str, list[dict]]:
    """Per-family list of {schedule, n_items, n_codes} from the line-item table.

    Drives the taxonomy-tree landing and the schedule enumeration. Keyed by
    form_family ('y9c' / 'call').
    """
    rows = _rows(
        "SELECT form_family, schedule, COUNT(*) AS n_items, "
        "COUNT(DISTINCT mdrm_code) AS n_codes "
        "FROM dict_schedule_lineitems WHERE schedule IS NOT NULL "
        "GROUP BY form_family, schedule ORDER BY form_family, schedule"
    )
    out: dict[str, list[dict]] = {}
    for r in rows:
        out.setdefault(r["form_family"], []).append(r)
    return out


def _schedule_one_liner(form_family: str, schedule: str) -> str:
    """One-line description for a schedule (from explanations.json title)."""
    blk = EXPLANATIONS.get("schedules", {}).get(schedule, {})
    return blk.get("title", "")


def _dict_search(q: str, page: int) -> tuple[list[dict], int]:
    """Server-side search over the dict taxonomy slice.

    Searches mdrm/UBPR codes, item descriptions/captions, and schedule names over
    the union of `dict_schedule_lineitems` and `dict_ubpr_concepts`. Returns one row
    per (code) with family/schedule/line/caption + a count of taxonomy relationships
    that reference the code (the "validated-relationship count"). Parameterized —
    the search term is bound, never interpolated. Paginated at _DICT_PAGE_SIZE.
    """
    like = f"%{q.strip()}%"
    # Per-code relationship counts: a relationship references a code when its
    # `codes` list contains that code. We pre-aggregate validated relationships
    # (status confirms the edit holds in the bulk data) per code via a join table.
    base = """
        WITH lineitems AS (
            SELECT mdrm_code AS code, form_family AS family, schedule, line_number AS line,
                   item_description AS caption, 'schedule' AS kind
            FROM dict_schedule_lineitems
            WHERE mdrm_code IS NOT NULL AND mdrm_code <> ''
        ),
        ubpr AS (
            SELECT ubpr_code AS code, 'ubpr' AS family, category AS schedule, NULL AS line,
                   caption, 'ubpr' AS kind
            FROM dict_ubpr_concepts
            WHERE ubpr_code IS NOT NULL AND ubpr_code <> ''
        ),
        catalog AS (
            SELECT code, ANY_VALUE(family) AS family, ANY_VALUE(schedule) AS schedule,
                   ANY_VALUE(line) AS line, ANY_VALUE(caption) AS caption,
                   ANY_VALUE(kind) AS kind
            FROM (SELECT * FROM lineitems UNION ALL SELECT * FROM ubpr)
            GROUP BY code
        ),
        relcounts AS (
            SELECT c.code,
                   COUNT(*) FILTER (WHERE r.status IN
                       ('CONFIRMED','CONFIRMED_CURRENT','VINTAGE_CONFIRMED','LOW_N_PASS')
                   ) AS n_validated
            FROM catalog c
            JOIN dict_relationships_summary r
              ON r.codes IS NOT NULL AND position(c.code IN r.codes) > 0
            GROUP BY c.code
        )
        SELECT cat.code, cat.family, cat.schedule, cat.line, cat.caption, cat.kind,
               COALESCE(rc.n_validated, 0) AS n_validated
        FROM catalog cat
        LEFT JOIN relcounts rc ON rc.code = cat.code
        WHERE (? = '' OR lower(cat.code) LIKE lower(?) OR lower(cat.caption) LIKE lower(?)
               OR lower(COALESCE(cat.schedule,'')) LIKE lower(?))
    """
    count_sql = f"SELECT COUNT(*) AS n FROM ({base}) _c"
    params = [q.strip(), like, like, like]
    total = _rows(count_sql, params)[0]["n"]
    offset = max(0, page - 1) * _DICT_PAGE_SIZE
    page_sql = base + " ORDER BY cat.code LIMIT ? OFFSET ?"
    rows = _rows(page_sql, params + [_DICT_PAGE_SIZE, offset])
    for r in rows:
        r["ref_url"] = _dict_ref_url(r.get("family"), r.get("schedule"))
    return rows, total


@app.get("/dictionary", response_class=HTMLResponse)
def dictionary(
    request: Request,
    q: str = Query("", max_length=120),
    page: int = Query(1, ge=1),
) -> HTMLResponse:
    """Taxonomy-tree landing + server-side variable search over the dict slice.

    When a query is present, the search-results grid is shown; the taxonomy tree
    (source families -> schedules) is always rendered as the browse surface.
    """
    rows, total = _dict_search(q, page) if q.strip() else ([], 0)
    n_pages = max(1, -(-total // _DICT_PAGE_SIZE)) if q.strip() else 1
    page = min(page, n_pages)
    meta = _dict_meta()

    # Build the taxonomy tree: each source family with its schedules (or a single
    # layer card for derivation layers that have no line-item schedules).
    sched_index = _dict_schedule_index()
    families: list[dict] = []
    n_schedules = 0
    for fam in _DICT_FAMILIES:
        entry = {
            "key": fam["key"],
            "label": fam["label"],
            "kind": fam["kind"],
            "category": EXPLANATIONS.get("categories", {}).get(fam["key"], {}),
        }
        if fam["kind"] == "schedules":
            scheds = []
            for s in sched_index.get(fam["family"], []):
                scheds.append({
                    "schedule": s["schedule"],
                    "n_items": s["n_items"],
                    "n_codes": s["n_codes"],
                    "title": _schedule_one_liner(fam["family"], s["schedule"]),
                    "code": _schedule_slug(fam["family"], s["schedule"]),
                })
            entry["schedules"] = scheds
            n_schedules += len(scheds)
        else:
            entry["layer"] = EXPLANATIONS.get("layers", {}).get(fam["layer"], {})
            entry["layer_key"] = fam["layer"]
        families.append(entry)

    # Headline numbers (preserved + extended).
    n_codes = _rows(
        "SELECT COUNT(*) AS n FROM ("
        "  SELECT mdrm_code AS c FROM dict_schedule_lineitems WHERE mdrm_code <> '' "
        "  UNION SELECT ubpr_code FROM dict_ubpr_concepts WHERE ubpr_code <> '') _u"
    )[0]["n"]
    n_rels = _rows("SELECT COUNT(*) AS n FROM dict_relationships_summary")[0]["n"]

    return templates.TemplateResponse(
        "dictionary.html",
        {
            "request": request,
            "q": q,
            "rows": rows,
            "total": total,
            "page": page,
            "n_pages": n_pages,
            "page_size": _DICT_PAGE_SIZE,
            "meta": meta,
            "ref_base": DICT_REF_BASE,
            "families": families,
            "n_schedules": n_schedules,
            "n_codes": n_codes,
            "n_rels": n_rels,
        },
    )


# ---------------- /dictionary/schedule/{code} — one schedule page ----------------

def _parse_schedule_slug(code: str) -> tuple[str, str] | None:
    """Resolve a slug like 'call_RC' / 'y9c_HC-B' to (form_family, schedule)."""
    if "_" not in code:
        return None
    fam, _, sched = code.partition("_")
    fam = fam.strip().lower()
    sched = sched.replace("-", "-").strip().upper()
    if fam not in ("call", "y9c"):
        return None
    hit = _rows(
        "SELECT DISTINCT form_family, schedule FROM dict_schedule_lineitems "
        "WHERE form_family = ? AND upper(schedule) = ?",
        [fam, sched],
    )
    if not hit:
        return None
    return hit[0]["form_family"], hit[0]["schedule"]


def _schedule_lineitems(form_family: str, schedule: str) -> list[dict]:
    """Full ordered line-item grid for a schedule (the columns the table has)."""
    return _rows(
        "SELECT line_number, mdrm_code, item_description, column_role, forms, "
        "start_date, notes FROM dict_schedule_lineitems "
        "WHERE form_family = ? AND schedule = ? "
        "ORDER BY try_cast(line_number AS DOUBLE) NULLS LAST, line_number, mdrm_code",
        [form_family, schedule],
    )


def _schedule_relationship_highlights(codes: list[str], limit: int = 8) -> list[dict]:
    """Top validated/identity relationships that touch this schedule's codes.

    A relationship 'touches' the schedule when its pipe-delimited `codes` list
    contains any of the schedule's MDRM codes. Ranked by empirical n (coverage),
    preferring identity/ratio kinds with a real pass rate.
    """
    if not codes:
        return []
    # Build an OR of position() probes — codes are bound, never interpolated.
    probes = " OR ".join(["position(? IN codes) > 0"] * len(codes))
    sql = (
        "SELECT rel_id, kind, status, expression, empirical_pass_rate, empirical_n "
        "FROM dict_relationships_summary "
        f"WHERE codes IS NOT NULL AND ({probes}) "
        "AND empirical_pass_rate IS NOT NULL "
        "ORDER BY try_cast(empirical_n AS BIGINT) DESC NULLS LAST LIMIT ?"
    )
    rows = _rows(sql, list(codes) + [limit])
    for r in rows:
        try:
            r["pass_pct"] = f"{float(r['empirical_pass_rate']) * 100:.1f}%"
        except (TypeError, ValueError):
            r["pass_pct"] = "—"
        try:
            r["n_h"] = f"{int(r['empirical_n']):,}"
        except (TypeError, ValueError):
            r["n_h"] = "—"
    return rows


# The warehouse view a schedule's data is exposed through (access info).
_SCHEDULE_VIEW = {
    ("call", "RC"): "sched_call_rc", ("call", "RC-B"): "sched_call_rc_b",
    ("call", "RC-C"): "sched_call_rc_c", ("call", "RC-E"): "sched_call_rc_e",
    ("call", "RC-N"): "sched_call_rc_n", ("call", "RC-R"): "sched_call_rc_r",
    ("call", "RI"): "sched_call_ri",
}


def _schedule_view_name(form_family: str, schedule: str, codes: list[str]) -> str:
    """The shaped warehouse view that exposes this schedule, if known.

    Prefer the access map's recorded shaped view for the schedule's codes (the
    real, data-derived mapping); fall back to the static Call map.
    """
    if codes:
        probes = ",".join(["?"] * len(codes))
        hit = _rows(
            f"SELECT shaped_views, COUNT(*) AS n FROM dict_variable_access_map "
            f"WHERE variable_id IN ({probes}) AND shaped_views <> '' "
            "GROUP BY shaped_views ORDER BY n DESC LIMIT 1",
            list(codes),
        )
        if hit and hit[0]["shaped_views"]:
            # shaped_views may be a comma/pipe list — take the first entry.
            first = re.split(r"[,|]", hit[0]["shaped_views"])[0].strip()
            if first:
                return first
    return _SCHEDULE_VIEW.get((form_family, schedule), "")


@app.get("/dictionary/schedule/{code}", response_class=HTMLResponse)
def dictionary_schedule(request: Request, code: str) -> HTMLResponse:
    """One schedule page: explanation, full line-item grid, relationship
    highlights, access info, and a per-schedule download corner."""
    parsed = _parse_schedule_slug(code)
    if parsed is None:
        raise HTTPException(status_code=404, detail=f"Unknown schedule: {code}")
    form_family, schedule = parsed
    slug = _schedule_slug(form_family, schedule)
    items = _schedule_lineitems(form_family, schedule)
    codes = sorted({r["mdrm_code"] for r in items if r.get("mdrm_code")})
    explain = EXPLANATIONS.get("schedules", {}).get(schedule, {})
    rels = _schedule_relationship_highlights(codes)
    view = _schedule_view_name(form_family, schedule, codes)
    fam_label = {"call": "Call Report", "y9c": "FR Y-9C"}.get(form_family, form_family)
    dict_parquet = (
        "https://data.freenic.org/dict_schedule_lineitems.parquet"
    )
    return templates.TemplateResponse(
        "schedule.html",
        {
            "request": request,
            "form_family": form_family,
            "fam_label": fam_label,
            "schedule": schedule,
            "slug": slug,
            "items": items,
            "n_items": len(items),
            "n_codes": len(codes),
            "explain": explain,
            "rels": rels,
            "view": view,
            "csv_url": f"/static/dictionary_csv/{slug}.csv",
            "dict_parquet": dict_parquet,
            "ref_url": _dict_ref_url(form_family, schedule),
            "meta": _dict_meta(),
        },
    )


# ---------------- /dictionary/variable/{mnemonic} — one variable page ----------------

def _variable_record(mnemonic: str) -> dict | None:
    """Resolve a variable mnemonic to its dict record (line-item OR UBPR).

    Returns None for unknown codes (the route 404s cleanly).
    """
    code = mnemonic.strip().upper()
    li = _rows(
        "SELECT form_family, schedule, line_number, item_description, column_role, "
        "mdrm_code, forms, start_date, notes FROM dict_schedule_lineitems "
        "WHERE upper(mdrm_code) = ? "
        "ORDER BY try_cast(line_number AS DOUBLE) NULLS LAST LIMIT 1",
        [code],
    )
    if li:
        r = li[0]
        return {
            "kind": "lineitem", "code": r["mdrm_code"],
            "name": r["item_description"], "form_family": r["form_family"],
            "schedule": r["schedule"], "line_number": r["line_number"],
            "column_role": r["column_role"], "forms": r["forms"],
            "start_date": r["start_date"], "notes": r["notes"],
            "schedule_slug": _schedule_slug(r["form_family"], r["schedule"])
            if r["schedule"] else "",
        }
    ub = _rows(
        "SELECT ubpr_code, caption, category, derivation, inputs, validated, "
        "empirical_agreement_rate, notes FROM dict_ubpr_concepts "
        "WHERE upper(ubpr_code) = ? LIMIT 1",
        [code],
    )
    if ub:
        r = ub[0]
        return {
            "kind": "ubpr", "code": r["ubpr_code"], "name": r["caption"],
            "category": r["category"], "derivation": r["derivation"],
            "inputs": r["inputs"], "validated": r["validated"],
            "agreement": r["empirical_agreement_rate"], "notes": r["notes"],
        }
    return None


def _variable_access(code: str) -> list[dict]:
    """Which base table / views expose a variable (from the access map)."""
    return _rows(
        "SELECT base_table, n_obs, raw_view, shaped_views FROM dict_variable_access_map "
        "WHERE upper(variable_id) = ?",
        [code.strip().upper()],
    )


def _variable_relationships(code: str, limit: int = 25) -> list[dict]:
    """Relationships whose codes list references this variable."""
    rows = _rows(
        "SELECT rel_id, scope, kind, status, expression, empirical_pass_rate, "
        "empirical_n FROM dict_relationships_summary "
        "WHERE codes IS NOT NULL AND position(? IN codes) > 0 "
        "ORDER BY try_cast(empirical_n AS BIGINT) DESC NULLS LAST LIMIT ?",
        [code.strip().upper(), limit],
    )
    for r in rows:
        try:
            r["pass_pct"] = f"{float(r['empirical_pass_rate']) * 100:.1f}%"
        except (TypeError, ValueError):
            r["pass_pct"] = "—"
    return rows


@app.get("/dictionary/variable/{mnemonic}", response_class=HTMLResponse)
def dictionary_variable(request: Request, mnemonic: str) -> HTMLResponse:
    """One variable page: definition, schedule placement, MDRM attributes,
    relationships it appears in, and which views expose it. 404 for unknowns."""
    rec = _variable_record(mnemonic)
    if rec is None:
        raise HTTPException(status_code=404, detail=f"Unknown variable: {mnemonic}")
    access = _variable_access(rec["code"])
    rels = _variable_relationships(rec["code"])
    return templates.TemplateResponse(
        "variable.html",
        {
            "request": request,
            "v": rec,
            "access": access,
            "rels": rels,
            "n_rels": len(rels),
            "ref_url": _dict_ref_url(rec.get("form_family"), rec.get("schedule")),
            "meta": _dict_meta(),
        },
    )


# ---------------- /sources — annotated supplier directory ----------------

@app.get("/sources", response_class=HTMLResponse)
def sources_page(request: Request) -> HTMLResponse:
    """The reviewed annotated directory of official data suppliers we use."""
    return templates.TemplateResponse(
        "sources.html",
        {"request": request, "sources": SOURCES_DIRECTORY.get("sources", [])},
    )


# ---------------- Wave-3 blueprint sections: Data / Code / Methodology ----------------

def _human_bytes(n: int) -> str:
    """Human-readable size for the release catalog (KB/MB/GB)."""
    for unit, div in (("GB", 1_073_741_824), ("MB", 1_048_576), ("KB", 1_024)):
        if n >= div:
            return f"{n / div:.1f} {unit}"
    return f"{n} B"


def _release_manifest() -> dict:
    """Baked inventory of the full v1.0 parquet release (file/size/sha/provenance).

    Generated on the build host from the FreeNIC warehouse export dir (parquet
    dir + SHA256SUMS.txt + PROVENANCE.csv). The full release is NOT shipped in the
    container — this is the catalog with per-file data.freenic.org URLs.
    """
    path = DATA / "release_manifest.json"
    if not path.exists():
        return {"n_files": 0, "total_bytes": 0, "files": []}
    with open(path, encoding="utf-8") as fh:
        m = json.load(fh)
    for f in m.get("files", []):
        f["size_h"] = _human_bytes(f.get("bytes", 0))
        f["url"] = f"https://data.freenic.org/{f['file']}"
    m["total_h"] = _human_bytes(m.get("total_bytes", 0))
    return m


@app.get("/data", response_class=HTMLResponse)
def data_page(request: Request) -> HTMLResponse:
    items = downloads.catalog()
    groups: dict[str, list[dict]] = {}
    for it in items:
        groups.setdefault(it["group"], []).append(it)
    total_rows = sum(it["n_rows"] for it in items)
    return templates.TemplateResponse(
        "data.html",
        {"request": request, "groups": groups, "n_items": len(items),
         "total_rows": total_rows, "release": _release_manifest()},
    )


@app.get("/code", response_class=HTMLResponse)
def code_page(request: Request) -> HTMLResponse:
    return templates.TemplateResponse("code.html", {"request": request})


@app.get("/api-docs", response_class=HTMLResponse)
def api_docs(request: Request) -> HTMLResponse:
    """Access-layer documentation: on-site REST/JSON endpoints, the DuckDB httpfs
    pattern against data.freenic.org, and the freenic_py / freenic_r / MCP
    quickstarts. Pure docs over the real layers."""
    return templates.TemplateResponse(
        "api.html", {"request": request, "tables": sorted(SLICE_TABLES)}
    )


def _slice_tables() -> list[dict]:
    """Live (table, n_rows, n_cols) for the real slice — drives the methodology page."""
    out: list[dict] = []
    for it in downloads.catalog():
        out.append({"table": it["table"], "n_rows": it["n_rows"],
                    "n_cols": len(it["columns"]), "desc": it["desc"]})
    return out


@app.get("/methodology", response_class=HTMLResponse)
def methodology(request: Request) -> HTMLResponse:
    dpr_text = ""
    for cand in (BASE.parent / "DPR.md", BASE / "DPR.md"):
        if cand.exists():
            dpr_text = cand.read_text(encoding="utf-8")
            break
    return templates.TemplateResponse(
        "methodology.html",
        {
            "request": request,
            "sources": SOURCES["sources"],
            "provenance": SOURCES.get("_provenance", ""),
            "slice_tables": _slice_tables(),
            "allowed_tables": sorted(SLICE_TABLES),
            "dpr_text": dpr_text,
        },
    )


# ---------------- Download routes — correct content-types per format ----------------

@app.get("/api/download/bulk/freenic_slice.zip")
def download_bulk() -> Response:
    raw, media, fname = downloads.bulk_zip()
    return Response(
        content=raw, media_type=media,
        headers={"Content-Disposition": f'attachment; filename="{fname}"'},
    )


@app.get("/api/code/repro_bundle.zip")
def download_repro() -> Response:
    raw, media, fname = downloads.repro_bundle_zip()
    return Response(
        content=raw, media_type=media,
        headers={"Content-Disposition": f'attachment; filename="{fname}"'},
    )


@app.get("/api/download/{artifact_id}")
def download_artifact(artifact_id: str) -> Response:
    art = downloads.get_artifact(artifact_id)
    if art is None:
        raise HTTPException(status_code=404, detail=f"Unknown artifact: {artifact_id}")
    raw, media, fname = downloads.render_artifact(art)
    return Response(
        content=raw, media_type=media,
        headers={"Content-Disposition": f'attachment; filename="{fname}"'},
    )


# ---------------- JSON APIs over the real slice ----------------

@app.get("/api/failures_by_year")
def api_failures_by_year() -> JSONResponse:
    return JSONResponse(_rows(
        "SELECT year, n_failures, total_assets, total_loss "
        "FROM agg_failures_by_year ORDER BY year"
    ))


@app.get("/api/failures_by_state")
def api_failures_by_state(limit: int = Query(20, ge=1, le=60)) -> JSONResponse:
    return JSONResponse(_rows(
        "SELECT state_code, n_failures, total_assets "
        "FROM agg_failures_by_state ORDER BY n_failures DESC LIMIT ?",
        [limit],
    ))


@app.get("/api/top_failures")
def api_top_failures(limit: int = Query(25, ge=1, le=100)) -> JSONResponse:
    return JSONResponse(_rows(
        "SELECT bank_name, city, state_code, failure_year, total_assets, "
        "estimated_loss, resolution_type "
        "FROM bank_failures WHERE total_assets IS NOT NULL "
        "ORDER BY total_assets DESC LIMIT ?",
        [limit],
    ))


@app.get("/api/institutions_by_type")
def api_institutions_by_type() -> JSONResponse:
    return JSONResponse(_rows(
        "SELECT entity_type, n FROM agg_institutions_by_type ORDER BY n DESC"
    ))


@app.get("/api/institutions_by_state")
def api_institutions_by_state(limit: int = Query(20, ge=1, le=60)) -> JSONResponse:
    return JSONResponse(_rows(
        "SELECT state_code, n FROM agg_institutions_by_state "
        "ORDER BY n DESC LIMIT ?",
        [limit],
    ))


@app.get("/api/fred_catalog")
def api_fred_catalog() -> JSONResponse:
    return JSONResponse(_rows(
        "SELECT series_id, series_name, n_obs, "
        "CAST(first_date AS VARCHAR) AS first_date, "
        "CAST(last_date AS VARCHAR) AS last_date "
        "FROM fred_catalog ORDER BY series_id"
    ))


@app.get("/api/fred_series")
def api_fred_series(series_id: str = Query(...)) -> JSONResponse:
    # parameterized — series_id bound as a value, not interpolated
    rows = _rows(
        "SELECT CAST(observation_date AS VARCHAR) AS date, value FROM fred_series "
        "WHERE series_id = ? ORDER BY observation_date",
        [series_id],
    )
    name = ""
    nm = _rows("SELECT series_name FROM fred_catalog WHERE series_id = ?", [series_id])
    if nm:
        name = nm[0]["series_name"]
    return JSONResponse({"series_id": series_id, "series_name": name, "points": rows})


# Per-definition unit labels for the 163-year spine (UNITS DIFFER BY DEFINITION —
# the replicated spine deliberately does NOT harmonize units; a value series must
# never be spliced across definitions blindly). num_banks is a count for all defs.
_SPINE_DEFINITIONS = {
    "national_only":  {"label": "National banks only", "dollar_unit": "$ millions"},
    "member_banks":   {"label": "Fed member banks", "dollar_unit": "$ millions"},
    "all_insured":    {"label": "All FDIC-insured", "dollar_unit": "$ thousands"},
    "all_commercial": {"label": "All commercial banks", "dollar_unit": "$ billions"},
}
# The definitional junction years and what changes at each (drawn as vlines +
# annotations on the chart so a definitional break is never a silent splice).
_SPINE_JUNCTIONS = [
    {"year": 1896, "label": "1896 — state banks added"},
    {"year": 1914, "label": "1914 — Federal Reserve founded"},
    {"year": 1934, "label": "1934 — FDIC-insured universe"},
]
_SPINE_METRICS = ("num_banks", "total_deposits", "total_loans", "total_assets")


@app.get("/api/bank_aggregates")
def api_bank_aggregates(metric: str = Query("num_banks")) -> JSONResponse:
    """The replicated 163-year bank-aggregate spine for one metric, returned as one
    series PER DEFINITION so a definitional break is never a silent splice.

    Honest gaps: only the (year, definition) rows that exist in the spine are
    returned — missing years (e.g. national_only 1942–2025) come back as gaps, not
    interpolated. Units differ by definition and are NOT harmonized (see caption).
    """
    if metric not in _SPINE_METRICS:
        raise HTTPException(status_code=400, detail=f"Unknown metric: {metric}")
    rows = _rows(
        "SELECT year, definition, value FROM long_bank_aggregates_1863_2026 "
        "WHERE metric = ? ORDER BY definition, year",
        [metric],
    )
    # group into one ordered (x, y) series per definition present for this metric
    series: dict[str, dict] = {}
    for r in rows:
        d = r["definition"]
        s = series.setdefault(d, {"definition": d,
                                  "label": _SPINE_DEFINITIONS.get(d, {}).get("label", d),
                                  "dollar_unit": _SPINE_DEFINITIONS.get(d, {}).get("dollar_unit", ""),
                                  "x": [], "y": []})
        s["x"].append(r["year"])
        s["y"].append(r["value"])
    # stable, chronological-by-coverage order of the definitions
    order = ["national_only", "member_banks", "all_insured", "all_commercial"]
    out_series = [series[d] for d in order if d in series]
    return JSONResponse({
        "metric": metric,
        "metrics": list(_SPINE_METRICS),
        "is_count": metric == "num_banks",
        "junctions": _SPINE_JUNCTIONS,
        "series": out_series,
    })


@app.get("/api/lookup_institution")
def api_lookup_institution(
    q: str = Query("", min_length=0),
    entity_type: str = Query("", max_length=8),
    state: str = Query("", max_length=2),
    limit: int = Query(50, ge=1, le=200),
) -> JSONResponse:
    """Parameterized search over the real active-institutions slice.

    Matches the query against the legal/short name OR the RSSD id (when the query
    is numeric), with optional exact filters on entity_type and state_code. Every
    term is bound (?), never interpolated. Returns the trimmed real columns the
    slice carries — nothing derived or fabricated (date_established is not
    populated in the slice, so it comes back as-is and the UI shows it honestly).
    """
    q = q.strip()
    clauses: list[str] = []
    params: list = []
    if q:
        like = f"%{q}%"
        if q.isdigit():
            clauses.append(
                "(lower(name_legal) LIKE lower(?) OR lower(name_short) LIKE lower(?) "
                "OR CAST(rssd_id AS VARCHAR) = ? OR CAST(fdic_cert AS VARCHAR) = ?)"
            )
            params += [like, like, q, q]
        else:
            clauses.append("(lower(name_legal) LIKE lower(?) OR lower(name_short) LIKE lower(?))")
            params += [like, like]
    if entity_type.strip():
        clauses.append("entity_type = ?")
        params.append(entity_type.strip().upper())
    if state.strip():
        clauses.append("state_code = ?")
        params.append(state.strip().upper())
    if not clauses:
        return JSONResponse([])
    where = " AND ".join(clauses)
    rows = _rows(
        "SELECT rssd_id, name_legal, name_short, entity_type, charter_type, city, "
        "state_code, fdic_cert, CAST(date_established AS VARCHAR) AS date_established "
        f"FROM institutions_active WHERE {where} "
        "ORDER BY name_legal LIMIT ?",
        params + [limit],
    )
    return JSONResponse(rows)


@app.get("/api/institution_facets")
def api_institution_facets() -> JSONResponse:
    """Distinct entity_type + state_code values (with counts) for the /institutions
    lookup filter dropdowns. Real values off the slice — no invented labels."""
    return JSONResponse({
        "total": _rows("SELECT COUNT(*) AS n FROM institutions_active")[0]["n"],
        "entity_types": _rows(
            "SELECT entity_type AS value, COUNT(*) AS n FROM institutions_active "
            "WHERE entity_type IS NOT NULL AND entity_type <> '' "
            "GROUP BY entity_type ORDER BY n DESC"
        ),
        "states": _rows(
            "SELECT state_code AS value, COUNT(*) AS n FROM institutions_active "
            "WHERE state_code IS NOT NULL AND state_code <> '' "
            "GROUP BY state_code ORDER BY value"
        ),
    })


# ---------------- /failures — bank-failure explorer over the real slice ----------

@app.get("/api/failure_facets")
def api_failure_facets() -> JSONResponse:
    """Distinct filter values for the /failures explorer: states, resolution
    types, charter classes, and the real year range. Real values off the slice."""
    yr = _rows("SELECT MIN(failure_year) AS lo, MAX(failure_year) AS hi FROM bank_failures")[0]
    return JSONResponse({
        "total": _rows("SELECT COUNT(*) AS n FROM bank_failures")[0]["n"],
        "year_min": yr["lo"],
        "year_max": yr["hi"],
        "states": _rows(
            "SELECT state_code AS value, COUNT(*) AS n FROM bank_failures "
            "WHERE state_code IS NOT NULL AND state_code <> '' "
            "GROUP BY state_code ORDER BY value"
        ),
        "resolution_types": _rows(
            "SELECT resolution_type AS value, COUNT(*) AS n FROM bank_failures "
            "WHERE resolution_type IS NOT NULL AND resolution_type <> '' "
            "GROUP BY resolution_type ORDER BY n DESC"
        ),
        "charter_classes": _rows(
            "SELECT charter_class AS value, COUNT(*) AS n FROM bank_failures "
            "WHERE charter_class IS NOT NULL AND charter_class <> '' "
            "GROUP BY charter_class ORDER BY n DESC"
        ),
    })


@app.get("/api/failures")
def api_failures(
    year_from: int = Query(0, ge=0),
    year_to: int = Query(9999, ge=0),
    state: str = Query("", max_length=2),
    resolution_type: str = Query("", max_length=8),
    charter_class: str = Query("", max_length=8),
    limit: int = Query(5000, ge=1, le=10000),
) -> JSONResponse:
    """Filtered bank-failure records off the real slice (whole table is 4,115 rows,
    so the default cap returns every match). Every filter is bound (?). Returns the
    real columns; nulls stay null (never imputed)."""
    clauses = ["failure_year >= ?", "failure_year <= ?"]
    params: list = [year_from, year_to]
    if state.strip():
        clauses.append("state_code = ?")
        params.append(state.strip().upper())
    if resolution_type.strip():
        clauses.append("resolution_type = ?")
        params.append(resolution_type.strip().upper())
    if charter_class.strip():
        clauses.append("charter_class = ?")
        params.append(charter_class.strip().upper())
    where = " AND ".join(clauses)
    rows = _rows(
        "SELECT bank_name, city, state_code, CAST(closing_date AS VARCHAR) AS closing_date, "
        "failure_year, acquiring_institution, total_deposits, total_assets, estimated_loss, "
        "resolution_type, charter_class FROM bank_failures "
        f"WHERE {where} ORDER BY failure_year DESC, total_assets DESC NULLS LAST LIMIT ?",
        params + [limit],
    )
    return JSONResponse(rows)


# ---------------- Layer-3 usage beacon sink (TELEMETRY_STANDARD) ----------------

@app.post("/__track")
async def track_beacon(request: Request) -> Response:
    """First-party beacon sink for ark-track.js / ark-triad.js (TELEMETRY_STANDARD
    §4). The Carson telemetry ASGI middleware already records the request itself
    (service=freenic, path=/__track) into $CARSON_TELEMETRY_DB; this route just
    drains and acknowledges the beacon so it lands as a clean 204 instead of the
    404 the triad beacons previously hit (there was no /__track route). Same-origin
    sink mirrors deploy/shaikh (sibling FastAPI site) — no cookies, no PII, body is
    advisory only. See DATA_SERVING.md 'Telemetry' + TELEMETRY_STANDARD note."""
    try:
        await request.body()  # drain; content is advisory only
    except Exception:  # noqa: BLE001 — a beacon must never surface an error
        pass
    return Response(status_code=204)
